# Generated by Django 4.1.5 on 2023-07-09 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='is_subscribed',
        ),
    ]
