# Generated by Django 4.1.5 on 2023-02-12 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='data',
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='meet_link',
            field=models.URLField(default='meet.google.com', max_length=500),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='subscribed_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
