# Generated by Django 4.1.5 on 2023-02-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_remove_appointment_data_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='meet_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
